### model
model_name_or_path: Qwen/Qwen2.5-Coder-7B-Instruct
adapter_name_or_path: saves/source_code_only/qwen-7b/lora_sft

### method
stage: sft
do_predict: true
finetuning_type: lora

### dataset
eval_dataset: pseudo_code_test
template: qwen
cutoff_len: 4096
overwrite_cache: true
preprocessing_num_workers: 32

### output
output_dir: saves/source_code_only/qwen-7b/lora_sft_pred
overwrite_output_dir: true

### eval
per_device_eval_batch_size: 2
predict_with_generate: true
ddp_timeout: 180000000
