### model
model_name_or_path: infly/OpenCoder-1.5B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
deepspeed: examples/deepspeed/ds_z0_config.json

trust_remote_code: true

### dataset
dataset: pseudo_code_train
eval_dataset: pseudo_code_dev
template: opencoder
cutoff_len: 4096
# max_samples: 1000
overwrite_cache: true
# preprocessing_num_workers: 32

### output
output_dir: saves/pseudo_code/opencoder-1.5b/lora_sft
logging_steps: 10
save_strategy: epoch
# save_steps: 500
plot_loss: true
overwrite_output_dir: true
load_best_model_at_end: true
save_total_limit: 2

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
per_device_eval_batch_size: 2
eval_strategy: epoch
# eval_steps: 500
