### model
model_name_or_path: infly/OpenCoder-8B-Instruct
adapter_name_or_path: saves/source_code_pseudo_code/opencoder-8b/lora_sft

### method
stage: sft
do_predict: true
finetuning_type: lora

trust_remote_code: true

### dataset
eval_dataset: pseudo_code_test
template: opencoder
cutoff_len: 4096
overwrite_cache: true
# preprocessing_num_workers: 32

### output
output_dir: saves/source_code_pseudo_code/opencoder-8b/lora_sft_pred
overwrite_output_dir: true

### eval
per_device_eval_batch_size: 2
predict_with_generate: true
ddp_timeout: 180000000
